### ISSUE TITLE
Collection aggregation validation

### ISSUE THREAD

**Issue by dnd** [dryrb/dry-validation#37]
What's the recommended way(if possible) to validate aggregate values on a collection? Say I want the sum of all amounts in a nested collection to equal a value of the main object, or there should be at least n items in the collection with property y.

**Comment by solnic** [comment]
Depends. Please provide a specific use case, if possible :)

**Comment by dnd** [comment]
I suppose both of those would be my examples.

The sum of the item amounts should equal 100 here. So this would fail:
```ruby
{
  amount: 100,
  items: [
    {amount: 75},
    {amount: 20},
  ]
}
```

The user should have selected at most one document from category A and at least two from category B. This fails because of too many selections from category A:
```ruby
{
  documents: [
    {id: 1, category: 'A'},
    {id: 5, category: 'A'},
    {id: 2, category: 'B'},
    {id: 3, category: 'B'}
  ]
}
```

**Comment by solnic** [comment]
I've got good news and bad news. Good news is that you can define validation for these use cases. Bad news is that I found a bug in `each` validator which currently doesn't support `key` DSL :) I will fix it and push a new release soon.

Anyhow, here's how you can define validations for these use cases:

``` ruby
require 'dry-validation'

data = {
  amount: 100,
  items: [
    { amount: 75 },
    { amount: 20 }
  ]
}

schema = Class.new(Dry::Validation::Schema) do
  key(:amount) { |amount| amount.int? }
  key(:items) { |items| items.array? }

  rule(:valid_amount, sum?: [:amount, :items])

  def sum?(amount, items)
    items.map { |item| item[:amount] }.reduce(:+) == amount
  end
end.new

result = schema.call(data)

puts result.failures.inspect
# [#<Dry::Validation::Rule::Result::Value success?=false input=[100, [{:amount=>75}, {:amount=>20}]] rule=#<Dry::Validation::Rule::Group name=:valid_amount predicate=#<Dry::Validation::Predicate id=:sum?>>>]

data = {
  documents: [
    { id: 1, category: 'A' },
    { id: 5, category: 'A' },
    { id: 2, category: 'B' },
    { id: 3, category: 'B' }
  ]
}

schema = Class.new(Dry::Validation::Schema) do
  key(:documents) { |documents| documents.array? }

  rule(:valid_selection, unique_categories?: [:documents])

  def unique_categories?(documents)
    documents.group_by { |doc| doc[:category] }.values.map(&:size).all? { |v| v == 1 }
  end
end.new

result = schema.call(data)

puts result.failures.inspect
# [#<Dry::Validation::Rule::Result::Value success?=false input=[[{:id=>1, :category=>"A"}, {:id=>5, :category=>"A"}, {:id=>2, :category=>"B"}, {:id=>3, :category=>"B"}]] rule=#<Dry::Validation::Rule::Group name=:valid_selection predicate=#<Dry::Validation::Predicate id=:unique_categories?>>>]
```

Now, once I fix (or I should say, add the missing feature :)) the problem with `each` and `key`, you'll be able to define a stricter validation by ie doing `items.each { |item| item.key(:amount, &:int?) }`.

One more thing, the `rule` DSL **requires** you to define validations for its rules, otherwise it will not be executed, the reason for this is simple, we shouldn't run a rule that depends on values that were not validated as a prerequisite. I will improve that and make it raise an error if such rules are missing (right now it just quietly  does nothing).

I will leave this issue as open and mark it done once the problem with `each` + `key` is fixed :)

Hope this helps.
