### ISSUE TITLE
Abstract schema and form/schema in order to manually specify rules

### ISSUE THREAD

**Issue by kwando** [dryrb/dry-validation#48]
We are generating validation rules by converting our in-house schema to the dry-validation rule AST and then compile it into a an array of rules. Basically we want to have our rules in a Dry::Validation::Schema[::Form] object so we can reuse the validation process and error compilation that dry-validation provides.

Currently there is no way to do it properly, our options is to duplicate whatever Dry::Validation::Schema does or resort to monkey patching.

**Comment by solnic** [comment]
I'm gonna tweak the schema so that it can accept rules from the outside and it will append them to the built-in ones. If the built-in ones are not present then only the injected ones will be used, which I believe is what you need.

**Comment by kwando** [comment]
Yeah, sounds like exactly what I want. 

Basically I followed the wiki page https://github.com/dryrb/dry-validation/wiki/Rule-AST and you end up with an array of rules, but then you are on your own when trying to use them for anything useful =P

**Comment by bradrobertson** [comment]
Just wondering if this would help with a use-case we're interested in. We've always had to write custom validation objects for a survey service that we use. Basically, a person can configure their own survey with *some* questions requiring a response (not all).

In order to properly validate a survey submission, we need both the originating survey AND the submission itself. @solnic are you suggesting that "accept rules from the outside" might fit this particular use-case where the `presence` validation of a key on a form submission is dependent on something external?

**Comment by solnic** [comment]
@bradrobertson sounds like it, yes. You basically want to dynamically generate rules based on information from some external source.
