### ISSUE TITLE
Form: When a single validation isn't respected for an attribute, it returns all the errors

### ISSUE THREAD

**Issue by jodosha** [dryrb/dry-validation#51]
Hello :smile: 

I'm following the instructions from `examples/form.rb`

```ruby
require 'bundler/setup'
require 'dry-validation'
require 'dry/validation/schema/form'

class UserFormSchema < Dry::Validation::Schema::Form
  key(:email) {|value| value.str? & value.filled? }
  key(:age)   {|value| value.int? & value.gt?(18) }
end

schema = UserFormSchema.new
errors = schema.call({'email' => '', 'age' => '18'})

puts errors.inspect
puts ""
puts errors.messages.inspect

__END__

#<Dry::Validation::Schema::Result params={:email=>"", :age=>18} messages={:age=>[["age must be greater than 18", "age must be an integer"], 18], :email=>[["email must be filled"], ""]}>

{:age=>[["age must be greater than 18", "age must be an integer"], 18], :email=>[["email must be filled"], ""]}
```

There is only one violation for `age`: `18` isn't greater than `18`. **But** it also reports the other error `"age must be an integer"`.

If I do:

```ruby
errors = schema.call({'email' => '', 'age' => '19'})

__END__

#<Dry::Validation::Schema::Result params={:email=>"", :age=>19} messages={:email=>[["email must be filled"], ""]}>

{:email=>[["email must be filled"], ""]}
```

It accepts the string representation of the age `"19"` as an integer.

**Comment by solnic** [comment]
> There is only one violation for age: 18 isn't greater than 18. But it also reports the other error "age must be an integer".

Right, this is actually the expected behavior with the current implementation. This will be improved once error message compilation is optimized. The trick is to skip certain error messages when they make no sense, like in this case saying that something must be greater than 18 implies that it must be a number, so we can only display one error. I'm gonna improve that in the next release.

To give you a bit of a background - in dry-v error messages are a result of applying predicates *but* we also have *potential* error messages that we generate from rule definitions, and we call them "validation hints". It means that some specific rule might be violated and we have a specific error message for it but we also want to display additional information about other rules that *potentially* might be violated, so that the user knows about the requirements for a specific value.

This is a pretty tricky thing to implement, but it's doable :)

> It accepts the string representation of the age "19" as an integer.

It does because form schemas coerces input based on type expectations. I understand why it confused you though, and it's related to "validation hints".

**Comment by victormier** [comment]
Is there any change about this? I know it makes sense to explain the user what's expected, but in some cases (email uniqueness, for example) it might be interesting to be able to only display failing validations.
