### ISSUE TITLE
Examples are confusing

### ISSUE THREAD

**Issue by joshuaflanagan** [dryrb/dry-validation#60]
It would really help to see some examples of expected usage - not just how to define a schema, but how to *consume* a schema. All of the examples just show a call to `#messages`. Is that the intended API for determining if the input passed schema validation? If not, what is?

Also, it would be useful to include the expected output of the commands in the `examples` directory. The output from using those examples is very surprising to me, so I'm wondering if they are behaving as expected. For example, consider https://github.com/dryrb/dry-validation/blob/6447302f3b53766b29f29230831890a5cc3822e0/examples/form.rb

When I run that script I see:

```
>  errors = schema.call('email' => '', 'age' => '18').messages
# => {:age=>[["age must be greater than 18", "age must be an integer"], 18], :email=>[["email must be filled"], ""]}
```

So, I was curious what valid input would look like. Unfortunately, it looks very similar:

```
> errors = schema.call('email' => 'm@example.com', 'age' => 18).messages
# => {:age=>[["age must be greater than 18", "age must be an integer"], 18]}
```

Is this expected behavior?

**Comment by solnic** [comment]
Thanks for the report. I'll be improving docs (see wiki for more info).

> So, I was curious what valid input would look like. Unfortunately, it looks very similar:
> > ...
> Is this expected behavior?

For now, yes. dry-validation generates validation hints from rule definitions even when a predicate was not applied. I'll be working on optimizing that so that only relevant information will be returned. I can make a quick workaround for the specific case that you show and simply drop type-related messages by default when there are other messages from failed predicates but ultimately it needs a more sophisticated mechanism.

I'll be releasing 0.7.0 later this week with *huge* improvements in the DSL and improved error messages structure. I'll try to get rid of type-related hints too, but proper solution will be shipped with 0.8.0.
