### ISSUE TITLE
Nesting should work for more than one level

### ISSUE THREAD

**Issue by kwando** [dryrb/dry-validation#9]
```ruby
class Schema < Dry::Validation::Schema
  key(:name) { |n| n.filled? }
  key(:data) do |data|
    data.key(:invoice_address) do |invoice_address|
      %i[street zip city country].each do |f|
        invoice_address.key(f, &:filled?)
      end
    end
end

schema = Schema.new
schema.call({
                data: {
                    invoice_address: {}
                }
            })
```
```
/vendor/bundle/bundler/gems/dry-validation-57d86bbfc390/lib/dry/validation/rule.rb:61:in `block in call': undefined method `call' for :street:Symbol (NoMethodError
```

**Comment by solnic** [comment]
As discussed, this won't work, for generating rules programmatically you can use the rule ast and built-in compiler (info in the README).

FYI a block in the dsl must return last rule, because we're `and`-ing it with the outter rule. so every time you call `invoice_address.key` it adds new rule to `invoice_address` which may accumulate more than one rule, and if that block doesn't return a rule then we don't know what to `and`-with :) `each` returns that symbol array, so it can't work because that's what to whole block returns.

One more thing - we can come up with various interfaces to remove duplication. ie `invoice_address.filled?(:street, :zip, :country)` etc. Ideas welcome.

**Comment by kwando** [comment]
Yeah, sorry. Forgot to close this! I'm totally with you on why my code does not work.
